Parser ok, need to clean and norm

diff --git a/tests/tester b/tests/tester
--- a/tests/tester
+++ b/tests/tester
@@ -5,31 +5,30 @@ Y="\033[0;33m";
 R="\033[0;31m";
 NC="\033[0m";
 
-# Invalid maps tester
-MAPS_FOLDER=./tests/invalid/;
-MAPS=$(ls "$MAPS_FOLDER");
-echo "[INVALID MAPS]";
-for MAP in $MAPS; do
-	./cub3d "$MAPS_FOLDER$MAP" 2>/dev/null;
-	if [[ $? == 0 ]]; then
-		echo -en "${R}[FAIL]${NC}"
-	else
-		echo -en "${G}[OK]${NC}";
-	fi;
-	echo "[$MAP]"
-done;
-
-
 # Valid maps tester
 MAPS_FOLDER=./tests/valid/;
 MAPS=$(ls "$MAPS_FOLDER");
-echo -e "\n[VALID MAPS]";
+echo -e "\n[ VALID MAPS ]";
 for MAP in $MAPS; do
+	echo -n "[$MAP]"
 	./cub3d "$MAPS_FOLDER$MAP" 2>/dev/null;
 	if [[ $? == 0 ]]; then
-		echo -en "${G}[OK]${NC}";
+		echo -e "${G}[OK]${NC}";
 	else
-		echo -en "${R}[FAIL]${NC}"
+		echo -e "${R}[FAIL]${NC}"
 	fi;
+done;
+
+# Invalid maps tester
+MAPS_FOLDER=./tests/invalid/;
+MAPS=$(ls "$MAPS_FOLDER");
+echo "[ INVALID MAPS ]";
+for MAP in $MAPS; do
 	echo "[$MAP]"
+	./cub3d "$MAPS_FOLDER$MAP";
+	if [[ $? == 0 ]]; then
+		echo -e "${R}[FAIL]${NC}\n"
+	else
+		echo -e "${G}[OK]${NC}\n";
+	fi;
 done;
diff --git a/tests/tester_bonus b/tests/tester_bonus
--- a/tests/tester_bonus
+++ b/tests/tester_bonus
@@ -8,27 +8,27 @@ NC="\033[0m";
 # Valid BONUS maps tester
 MAPS_FOLDER=./tests/bonus_valid/;
 MAPS=$(ls "$MAPS_FOLDER");
-echo -e "\n[VALID BONUS MAPS]";
+echo -e "\n[ VALID BONUS MAPS ]";
 for MAP in $MAPS; do
+	echo -n "[$MAP]"
 	./cub3d "$MAPS_FOLDER$MAP" 2>/dev/null;
 	if [[ $? == 0 ]]; then
-		echo -en "${G}[OK]${NC}";
+		echo -e "${G}[OK]${NC}";
 	else
-		echo -en "${R}[FAIL]${NC}"
+		echo -e "${R}[FAIL]${NC}"
 	fi;
-	echo "[$MAP]"
 done;
 
 # Invalid BONUS maps tester
 MAPS_FOLDER=./tests/bonus_invalid/;
 MAPS=$(ls "$MAPS_FOLDER");
-echo -e "\n[INVALID BONUS MAPS]";
+echo -e "\n[ INVALID BONUS MAPS ]";
 for MAP in $MAPS; do
-	./cub3d "$MAPS_FOLDER$MAP" 2>/dev/null;
-	if [[ $? == 0 ]]; then
-		echo -en "${R}[FAIL]${NC}"
-	else
-		echo -en "${G}[OK]${NC}";
-	fi;
 	echo "[$MAP]"
+	./cub3d "$MAPS_FOLDER$MAP" ;
+	if [[ $? == 0 ]]; then
+		echo -e "${R}[FAIL]${NC}\n"
+	else
+		echo -e "${G}[OK]${NC}\n";
+	fi;
 done;
